=== wangmliang/springboot-demo/db/metadata/tools/lib/sims-rtplt-component-security/com/aspire/sims/rtplt/component/security/metadata2/dtds/Metadata_Auth_Main.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 元数据主文件 DTD-->
<!ELEMENT domain (resource-category+)>
<!ELEMENT resource-category (resource-category*, resource*)>
<!ELEMENT resource (operation*)>  
<!ELEMENT operation (address+)>
<!ELEMENT address (param1?, param2?, param3?)>
<!ELEMENT param1 EMPTY>
<!ELEMENT param2 EMPTY>
<!ELEMENT param3 EMPTY>

<!ATTLIST domain
	subsystem CDATA #REQUIRED
	oldSubsystem CDATA #IMPLIED
	id CDATA #REQUIRED
>
<!ATTLIST resource-category
	key CDATA #REQUIRED
	name CDATA #REQUIRED
	desc CDATA #IMPLIED
	orderKey CDATA #IMPLIED
>
<!ATTLIST resource
	key CDATA #REQUIRED
	name CDATA #REQUIRED
	desc CDATA #IMPLIED
	authType CDATA #IMPLIED
	orderKey CDATA #IMPLIED	
>
<!ATTLIST operation
	key CDATA #REQUIRED
	name CDATA #REQUIRED
	desc CDATA #IMPLIED	
	depend CDATA #IMPLIED
	orderKey CDATA #IMPLIED	
>
<!ATTLIST address
	name CDATA #REQUIRED
	url CDATA #REQUIRED
>
<!ATTLIST param1
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!ATTLIST param2
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!ATTLIST param3
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== wangmliang/springboot-demo/db/metadata/auth/metadata_auth_exclude_portal_admin_main.xml
<?xml version="1.0" encoding="gb2312"?>
<!DOCTYPE domain SYSTEM "Metadata_Auth_Main.dtd">
<domain id="admin" subsystem="exclude_portal_admin">
	<resource-category key="exclude_portal_admin" name="portal例外资源" desc="portal例外资源">
		<!-- session例外资源-->
		<resource key="exclude_portal_admin_session" name="session例外资源" desc="session例外资源" authType="UNAUTH">
			<operation key="EXCLUDE" name="例外" desc="例外">	
				<address name="登录action" url="/login"/>
				<address name="退出登录" url="/logout"/>
				<address name="404错误页面" url="/404.html"/>
				<address name="500错误页面" url="/pages/500.shtml"/>
				<address name="未授权提醒页面" url="/403"/>
				<address name="页面签权url" url="/auth/pageAuth"/>
			</operation>
		</resource>
			
		<!-- 鉴权例外资源-->
		<resource key="exclude_portal_admin_perm" name="鉴权例外资源" desc="鉴权例外资源" authType="LOGIN_AUTH">
			<operation key="EXCLUDE" name="前台鉴权例外" desc="登录后就可访问">
				<address name="首页菜单请求" url="/portal/menu.ajax"/>	
				<address name="首页" url="/index"/>
				<address name="取用户信息" url="/auth/staff/findLoginStaff"/>
				<address name="退出登录" url="/main.html"/>
				<address name="退出登录" url="/logout"/>
				<address name="个人管理页面" url="/auth/individual/modifyInfo"/>
				<address name="查询个人资料" url="/auth/staff/findLoginStaff"/>
				<address name="修改个人资料" url="/auth/staff/updateStaff"/>
				
				<address name="修改个人密码页面" url="/auth/individual/modifyPwd"/>
				<address name="修改个人密码" url="/auth/staff/changePwd"/>
			</operation>
		</resource>	
	</resource-category>
</domain>

=== wangmliang/springboot-demo/db/metadata/auth/metadata_auth_auth_admin_main.xml
<?xml version="1.0" encoding="gb2312"?>
<!DOCTYPE domain SYSTEM "Metadata_Auth_Main.dtd">
<domain id="admin" subsystem="auth">
	<!-- 资源分类－第一级 -->
	<resource-category key="auth_admin" orderKey="1000"  name="系统管理" desc="系统管理">
		<!-- 资源-->
		<resource-category key="auth_admin_sys_individual" name="个人管理" desc="个人管理">
			<resource key="auth_admin_sys_individual_modifyInfo" name="修改帐号信息" desc="修改帐号信息">
				<!-- 资源操作-DO -->
				<operation key="QUERY" name="修改" desc="修改">
					<address name="个人管理页面" url="/auth/individual/modifyInfo"/>
					<address name="查询个人资料" url="/auth/staff/findLoginStaff"/>
					<address name="修改个人资料" url="/auth/staff/updateStaff"/>
					<address name="查询个人扩展属性" url="/auth/staff/findStaffExtendProperties"/>
				</operation>
			</resource>
			<resource key="auth_admin_sys_individual_modifyPwd" name="修改个人密码" desc="修改个人密码">
				<!-- 资源操作-DO -->
				<operation key="QUERY" name="修改" desc="修改">
					<address name="修改个人密码页面" url="/auth/individual/modifyPwd"/>
					<address name="修改个人密码" url="/auth/staff/changePwd"/>
				</operation>
			</resource>
			<resource key="auth_admin_sys_individual_selfconfig" name="个性化参数设置" desc="个性化参数设置">
				<!-- 资源操作-DO -->
				<operation key="QUERY" name="查询" desc="查询">
					<address name="个性化参数修改页面" url="/auth/individual/selfConfigSetting"/>
					<address name="个性化参数查询" url="/auth/pendTaskSetting/get"/>
					<address name="个性化参数设置" url="/auth/pendTaskSetting/update"/>
				</operation>
			</resource>
		</resource-category>
		<resource-category key="auth_admin_sys_dept" name="组织管理" desc="组织管理">
				<resource key="auth_admin_sys_dept_deptManage" name="组织管理" desc="组织管理">
					<!-- 资源操作-->
					<operation key="QUERY" name="组织查询" desc="组织查询">
						<address name="组织管理页面" url="/auth/dept/page"/>
						<address name="组织树查询" url="/auth/department/listDepartmentTree"/>
						<address name="组织查询" url="/auth/department/findDepartment"/>
						<address name="组织详情查询" url="/auth/department/findDepartmentInfo"/>
						<address name="更新组织" url="/auth/department/updateDepartment"/>
						<address name="删除组织" url="/auth/department/delDepartment"/>
					</operation>
					<operation key="MODIFY" name="组织修改" desc="组织修改">
						<address name="更新组织" url="/auth/department/updateDepartment"/>
					</operation>
					<operation key="DELETE" name="组织删除" desc="组织删除">
						<address name="删除组织" url="/auth/department/delDepartment"/>
					</operation>
					<operation key="ROLE2DEPT" name="组织添加角色" desc="组织添加角色">
						<address name="添加组织角色" url="/auth/department/updateDepartmentRole"/>
						<address name="查询组织角色列表" url="/auth/department/listDepartmentRoles"/>
					</operation>
					<operation key="STAFF2DEPT" name="组织添加用户" desc="组织添加用户">
						<address name="查询组织用户列表" url="/auth/staff/listStaff"/>
						<address name="添加组织用户" url="/auth/staff/updateStaffDepartment"/>
					</operation>
					<operation key="AUTH2STAFF" name="组织成员授权" desc="组织成员授权">
						<address name="查询角色关联下用户列表" url="/auth/staff/listRoleByStaffIds"/>
						<address name="组织里用户权限修改" url="/auth/staff/updateStaffRolesDepartment"/>
					</operation>
				</resource>
				
		</resource-category>
		<resource-category key="auth_admin_sys_staff" name="成员管理" desc="成员管理">
			<resource key="auth_admin_sys_staff_staffManage" name="成员管理" desc="成员管理">
				<!-- 资源操作-->
				<operation key="QUERY" name="查询" desc="查询">
					<address name="成员管理页面" url="/auth/staff/page.html"/>
					<address name="查询请求" url="/auth/staff/listStaff.json"/>
				</operation>
				<operation key="ADD" name="创建" desc="创建用户">
					<address name="添加页面" url="/auth/staff/add.html"/>
					<address name="创建请求" url="/auth/staff/createStaff.json"/>
				</operation>
				
				<operation key="UPDATE" name="修改" desc="更新用户">
					<address name="修改页面" url="/auth/staff/edit.html"/>
					<address name="更新" url="/auth/staff/updateStaff.json"/>
				</operation>
				<operation key="DELETE" name="删除" desc="删除用户">
					<address name="删除请求" url="/auth/staff/deleteStaff.json"/>
				</operation>
				<operation key="LOCKSTAFF" name="锁定" desc="查询">
					<address name="锁定请求" url="/auth/staff/lockStaff.json"/>
				</operation>
				<operation key="RESETPWD" name="重置密码" desc="重置密码">
					<address name="重置密码请求" url="/auth/staff/resetPwd.json"/>
				</operation>
				<operation key="AUTHSTAFF" name="授权" desc="用户授权">
					<address name="获取用户详情" url="/auth/staff/findStaff.html"/>
					<address name="查询用户角色列表" url="/auth/staff/listStaffRoles"/>
					<address name="更新用户角色" url="/auth/staff/updateStaffRole"/>
				</operation>
			</resource>
		</resource-category>
		<resource-category key="auth_admin_sys_role" name="角色管理" desc="角色管理">
			<resource key="auth_admin_sys_role_roleManage" name="角色管理" desc="角色管理">
				<operation key="QUERY" name="查询" desc="查询">
					<address name="浏览角色页面" url="/auth/role/page.html"/>
					<address name="查看" url="/auth/role/listRoles.json"/>
				</operation>
				<operation key="ADD" name="新增角色" desc="新增角色" depend="QUERY">
					<address name="新增角色页面" url="/auth/role/add.html"/>
					<address name="添加" url="/auth/role/updateRole.json"/>
				</operation>
				<operation key="MODIFY" name="修改角色" desc="修改角色" depend="QUERY">
					<address name="编辑角色页面" url="/auth/role/edit.html"/>
					<address name="修改" url="/auth/role/updateRole.json"/>
				</operation>
				<operation key="DELETE" name="删除角色" desc="删除角色" depend="QUERY">
					<address name="删除角色" url="/auth/role/deleteRole.json"/>
				</operation>
				<operation key="AUTHROLE" name="角色关联权限" desc="角色关联权限">
					<address name="权限列表" url="/auth/role/listRoleResource.html"/>
					<address name="关联角色权限" url="/auth/role/updateRoleResource.json"/>
				</operation>
			</resource>
		</resource-category>
	</resource-category>
	
</domain>
